- name: Create file
  hosts: all
  become: yes
  tasks:
  - name: Create file with context
    copy:
      dest: /tmp/context_file
      content:
        Welcome to my Youtube channel. 
        Best regards from Morfei!
